-- 1. CREATE CUSTOM TYPES (ENUMS)
-- Enum for user roles
CREATE TYPE public.user_role AS ENUM (
    'GUEST',
    'SENDER',
    'TRANSPORTER',
    'RECEIVER'
);

-- Enum for parcel statuses
CREATE TYPE public.parcel_status AS ENUM (
    'PENDING',
    'MATCHED',
    'PICKED_UP',
    'IN_TRANSIT',
    'DELIVERED'
);


-- 2. CREATE PROFILES TABLE
-- This table stores public user data and is linked to the authenticated user.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    avatar_url TEXT,
    role public.user_role NOT NULL DEFAULT 'GUEST'
);

-- Function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, name, email, role)
    VALUES (new.id, new.raw_user_meta_data->>'name', new.email, (new.raw_user_meta_data->>'role')::public.user_role);
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function after a new user is created
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 3. CREATE PARCELS TABLE
CREATE TABLE public.parcels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sender_id UUID NOT NULL REFERENCES public.profiles(id),
    transporter_id UUID REFERENCES public.profiles(id),
    receiver_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    weight_kg NUMERIC(6, 2),
    size TEXT CHECK (size IN ('S', 'M', 'L', 'XL')),
    price NUMERIC(10, 2) NOT NULL,
    origin JSONB NOT NULL,
    destination JSONB NOT NULL,
    status public.parcel_status NOT NULL DEFAULT 'PENDING',
    tracking_code TEXT UNIQUE NOT NULL DEFAULT 'CC' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT), 1, 8)),
    images TEXT[]
);


-- 4. CREATE TRIPS TABLE
CREATE TABLE public.trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    transporter_id UUID NOT NULL REFERENCES public.profiles(id),
    origin JSONB NOT NULL,
    destination JSONB NOT NULL,
    departure_date TIMESTAMPTZ NOT NULL,
    capacity TEXT CHECK (capacity IN ('S', 'M', 'L', 'XL'))
);


-- 5. CREATE STORAGE BUCKETS
-- Create a bucket for parcel images with public read access
INSERT INTO storage.buckets (id, name, public)
VALUES ('parcel_images', 'parcel_images', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Create a bucket for user avatars with public read access
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Policies for parcel_images bucket
CREATE POLICY "Allow public read access on parcel_images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'parcel_images');

CREATE POLICY "Allow authenticated users to upload parcel_images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'parcel_images');

-- Policies for avatars bucket
CREATE POLICY "Allow public read access on avatars"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'avatars');

CREATE POLICY "Allow users to upload their own avatar"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'avatars' AND auth.uid() = (storage.foldername(name))[1]::uuid);

CREATE POLICY "Allow users to update their own avatar"
ON storage.objects FOR UPDATE
TO authenticated
USING (auth.uid() = (storage.foldername(name))[1]::uuid);


-- 6. SETUP ROW-LEVEL SECURITY (RLS)
-- Enable RLS for all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parcels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

-- RLS Policies for profiles
CREATE POLICY "Profiles are visible to everyone"
ON public.profiles FOR SELECT
TO public
USING (TRUE);

CREATE POLICY "Users can insert their own profile"
ON public.profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id);

-- RLS Policies for parcels
CREATE POLICY "Parcels are visible to senders, assigned transporters, and the public if pending"
ON public.parcels FOR SELECT
TO authenticated
USING (
    (auth.uid() = sender_id) OR
    (auth.uid() = transporter_id) OR
    (status = 'PENDING')
);

CREATE POLICY "Authenticated users can create parcels"
ON public.parcels FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Senders and transporters can update parcels"
ON public.parcels FOR UPDATE
TO authenticated
USING (
    (auth.uid() = sender_id AND status = 'PENDING') OR
    (auth.uid() = transporter_id) OR
    (status = 'PENDING' AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'TRANSPORTER')
);

CREATE POLICY "Senders can delete their own pending parcels"
ON public.parcels FOR DELETE
TO authenticated
USING (auth.uid() = sender_id AND status = 'PENDING');

-- RLS Policies for trips
CREATE POLICY "Trips are visible to everyone"
ON public.trips FOR SELECT
TO authenticated
USING (TRUE);

CREATE POLICY "Transporters can create trips"
ON public.trips FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = transporter_id AND
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'TRANSPORTER'
);

CREATE POLICY "Transporters can update their own trips"
ON public.trips FOR UPDATE
TO authenticated
USING (auth.uid() = transporter_id);

CREATE POLICY "Transporters can delete their own trips"
ON public.trips FOR DELETE
TO authenticated
USING (auth.uid() = transporter_id);
