-- 1. ADD NEW ENUM TYPES
CREATE TYPE public.trip_status AS ENUM (
    'ACTIVE',
    'COMPLETED',
    'CANCELLED'
);

CREATE TYPE public.request_status AS ENUM (
    'PENDING',
    'ACCEPTED',
    'DECLINED'
);

CREATE TYPE public.request_type AS ENUM (
    'SENDER_TO_TRAVELER',
    'TRAVELER_TO_SENDER'
);

-- 2. ALTER PROFILES TABLE
ALTER TABLE public.profiles
ADD COLUMN rating NUMERIC(3, 2) DEFAULT 0;

-- 3. ALTER TRIPS TABLE
ALTER TABLE public.trips
ADD COLUMN arrival_date TIMESTAMPTZ,
ADD COLUMN status public.trip_status NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN price NUMERIC(10, 2);

-- 4. CREATE REQUESTS TABLE
CREATE TABLE public.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    parcel_id BIGINT NOT NULL REFERENCES public.parcels(id),
    trip_id BIGINT REFERENCES public.trips(id),
    requester_id UUID NOT NULL REFERENCES public.profiles(id),
    requestee_id UUID NOT NULL REFERENCES public.profiles(id),
    status public.request_status NOT NULL DEFAULT 'PENDING',
    type public.request_type NOT NULL
);

-- 5. CREATE REVIEWS TABLE
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    parcel_id BIGINT NOT NULL REFERENCES public.parcels(id),
    reviewer_id UUID NOT NULL REFERENCES public.profiles(id),
    reviewee_id UUID NOT NULL REFERENCES public.profiles(id),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT
);

-- 6. SETUP ROW-LEVEL SECURITY (RLS) FOR NEW TABLES
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- RLS Policies for requests
CREATE POLICY "Requests are visible to the requester and requestee"
ON public.requests FOR SELECT
TO authenticated
USING (auth.uid() = requester_id OR auth.uid() = requestee_id);

CREATE POLICY "Users can create requests"
ON public.requests FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can update their own requests"
ON public.requests FOR UPDATE
TO authenticated
USING (auth.uid() = requestee_id);

-- RLS Policies for reviews
CREATE POLICY "Reviews are visible to everyone"
ON public.reviews FOR SELECT
TO public
USING (TRUE);

CREATE POLICY "Users can create reviews for parcels they were involved in"
ON public.reviews FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = reviewer_id AND
    (
        EXISTS (
            SELECT 1 FROM public.parcels
            WHERE id = parcel_id AND (sender_id = auth.uid() OR transporter_id = auth.uid())
        )
    )
);
