export const guelmaCities = [
  "Aïn Ben Beida",
  "Aïn Larbi",
  "Aïn Makhlouf",
  "Aïn Reggada",
  "Aïn Sandel",
  "Belkheir",
  "Ben Djerrah",
  "Beni Mezline",
  "Bordj Sabat",
  "Bou Hachana",
  "Bou Hamdane",
  "Bouati Mahmoud",
  "Bouchegouf",
  "Boumahra Ahmed",
  "Dahouara",
  "Djeballah Khemissi",
  "El Fedjoudj",
  "Guelaât Bou Sbaâ",
  "Guelma",
  "Hammam Debagh",
  "Hammam Nbail",
  "Héliopolis",
  "Houari Boumediene",
  "Kheraza",
  "Medjez Amar",
  "Medjez Sfa",
  "Nechmaya",
  "Oued Cheham",
  "Oued Fragha",
  "Oued Zenati",
  "Ras El Agba",
  "Roknia",
  "Salaoua Announa",
  "Tamlouka",
];
