export const guelmaCities = [
  "Aïn Ben Beida - عين بن بيضاء",
  "Aïn Larbi - عين العربي",
  "Aïn Makhlouf - عين مخلوف",
  "Aïn Reggada - عين رقادة",
  "Aïn Sandel - عين صندل",
  "Belkheir - بلخير",
  "Ben Djerrah - بن جراح",
  "Beni Mezline - بني مزلين",
  "Bordj Sabat - برج صباط",
  "Bou Hachana - بوحشانة",
  "Bou Hamdane - بوحمدان",
  "Bouati Mahmoud - بوعاطي محمود",
  "Bouchegouf - بوشقوف",
  "Boumahra Ahmed - بومهرة أحمد",
  "Dahouara - الداهوارة",
  "Djeballah Khemissi - جبالة الخميسي",
  "El Fedjoudj - الفجوج",
  "Guelaât Bou Sbaâ - قلعة بوصبع",
  "Guelma - قالمة",
  "Hammam Debagh - حمام دباغ",
  "Hammam Nbail - حمام النبايل",
  "Héliopolis - هليوبوليس",
  "Houari Boumediene - هواري بومدين",
  "Kheraza - خرازة",
  "Medjez Amar - مجاز عمار",
  "Medjez Sfa - مجاز الصفاء",
  "Nechmaya - نشماية",
  "Oued Cheham - وادي الشحم",
  "Oued Fragha - وادي فراغة",
  "Oued Zenati - وادي الزناتي",
  "Ras El Agba - رأس العقبة",
  "Roknia - الركنية",
  "Salaoua Announa - سلاوة عنونة",
  "Tamlouka - تاملوكة",
];